services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    expose:
      - "5000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
