services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    expose:
      - "5000"
    networks:
      - my_network
    volumes:
      - db_volume:/app/instance
  
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - flask
    networks:
      - my_network
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - my_network
    volumes:
      - db_volume:/app/instance
  
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat
    command: ["celery", "-A", "tasks.celery_app", "beat", "--loglevel=info"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    networks:
      - my_network
    volumes:
      - db_volume:/app/instance
  
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - my_network
  

networks:
  my_network:

volumes:
  db_volume:

# uixie.porkbun.com