name: Deploy to AWS

on:
  push:
    branches:
      - master
      - impl-workflows
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_ARN}}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: flask
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     echo $REGISTRY
      #     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Trigger secrets-app-tf repo workflow with commit SHA
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/ravilladhaneesh/secrets-app-tf/dispatches \
            -d '{
                  "event_type": "deploy-with-sha",
                  "client_payload": {
                    "sha": "'${GITHUB_SHA}'"
                  }
                }'