name: Deploy to AWS

on:
  push:
    branches:
      - master
      - impl-workflows
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_ARN}}
          aws-region: ap-south-1

      